# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qte/contract/v1/envelope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qte/contract/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eqte/contract/v1/envelope.proto\x12\x0fqte.contract.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x8f\x01\n\x08\x45nvelope\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x03seq\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x07sent_at\x18\x04 \x01(\x03H\x01\x88\x01\x01\x12(\n\x07payload\x18\x05 \x01(\x0b\x32\x17.google.protobuf.StructB\x06\n\x04_seqB\n\n\x08_sent_atB8Z6qte-platform/schemas/gen/go/qte/contract/v1;contractv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qte_sdk.contract.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6qte-platform/schemas/gen/go/qte/contract/v1;contractv1'
  _globals['_ENVELOPE']._serialized_start=82
  _globals['_ENVELOPE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
